StudentOrganization/StudentOrganization/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('main.urls', namespace="main")),
    url(r'^events/', include('events.urls', namespace="events")),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^admin/', include(admin.site.urls)),
)

StudentOrganization/events/urls.py
from django.conf.urls import patterns, url

from events import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<event_id>\d+)/$', views.detail, name='detail'),
    url(r'^create', views.create, name='create'),
	url(r'^list', views.list, name='list'),
)

StudentOrganization/main/urls.py
from django.conf.urls import patterns, url

from main import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index')
)

StudentOrganization/users/urls.py
from django.conf.urls import patterns, url

from users import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<user_id>\d+)/$', views.detail, name='detail'),
	url(r'^list', views.list, name='list'),
)

StudentOrganization/events/models.py
from django.db import models
from django.contrib.auth.models import User

class Event(models.Model):
    event_creator = models.ForeignKey(User)
    event_name = models.CharField(max_length=128)
    event_date = models.DateTimeField('Event date')
    event_creation = models.DateTimeField('Date created')
    event_text = models.CharField(max_length=4096)

StudentOrganization/users/models.py
from django.db import models

# Create your models here.

StudentOrganization/events/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from django.template import RequestContext, loader
from models import Event
from django.contrib.auth.models import User

# Create your views here.
def index(request):
	return render(request, 'events/index.html')	

def detail(request, event_id):
	event = get_object_or_404(Event, id=event_id)
	user = User.objects.get(id=event.event_creator_id)
	return render(request, 'events/detail.html', {"event" : event, "owner" : user})

def create(request):
	return render(request, 'events/create.html')
	
def list(request):
	return render(request, 'events/list.html', {"events" : Event.objects.all()})

StudentOrganization/main/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
	return render(request, 'main/index.html', {"user" : request.user})

StudentOrganization/users/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from django.template import RequestContext, loader
from django.contrib.auth.models import User

# Create your views here.
def index(request):
	return render(request, 'users/index.html', {"users" : User.objects.all()})

def detail(request, user_id):
	user = get_object_or_404(User, id=user_id)
	return render(request, 'users/detail.html', {"user" : user})
	
def list(request):
	return render(request, 'users/list.html', {"users" : User.objects.all()})

StudentOrganization/templates/events/create.html
{% include "header.html" %}

<h1>Create an Event</h1>
TODO...
Submit button would submit to database, facebook, and google

{% include "footer.html" %}

StudentOrganization/templates/events/detail.html
{% include "header.html" %}

<h1>{{event.event_name|title}}</h1>
<h2>Date:</h2>
{{event.event_date}} <br/>
{% if event.event_date|timeuntil == "0 minutes" %}
({{event.event_date|timesince}} ago)
{% else %}
(in {{event.event_date|timeuntil}})
{% endif %}
<h2>Description:</h2>
{{event.event_text}}
<h2>Created On:</h2>
{{event.event_creation}}
<h2>Created By:</h2>
<a href="{% url 'users:detail' owner.id %}">{{owner.first_name}} {{owner.last_name}}</a>

{% include "footer.html" %}

StudentOrganization/templates/events/index.html
{% include "header.html" %}

<h1>Events</h1>
<h2>Actions</h2>
<ul>
<li><a href="{% url 'events:create' %}">Create Event</a></li>
<li><a href="{% url 'events:list' %}">List Events</a></li>
</ul>

{% include "footer.html" %}

StudentOrganization/templates/events/list.html
{% include "header.html" %}

{% for event in events %}
<a href="{% url 'events:detail' event.id %}">{{ event.event_name }}</a> <br/>
{% empty %}
No events exist
{% endfor %}

{% include "footer.html" %}

StudentOrganization/templates/footer.html
<br/>
... Footer text ...
<br/>

StudentOrganization/templates/header.html
<h1><a href="{% url 'main:index' %}">Home</a></h1>

StudentOrganization/templates/main/index.html
{% include "header.html" %}

{% if user %}
<h1>Welcome, {{user.username}}!</h1>
<ul>
<li><a href="todo">Log out</a></li>
<li><a href="{% url 'events:index' %}">Events Index</a></li>
<li><a href="{% url 'users:index' %}">Users Index</a></li>
</ul>
{% else %}
<h1>Welcome!</h1>
<li><a href="todo">Log in</a></li>
{% endif %}

{% include "footer.html" %}

StudentOrganization/templates/users/detail.html
{% include "header.html" %}

<h1>{{user.first_name}} {{user.last_name}}</h1>
<h2>Username:</h2>
{{user.username}}
<h2>Email:</h2>
<a href="mailto:{{user.email}}">{{user.email}}</a>

{% include "footer.html" %}

StudentOrganization/templates/users/index.html
{% include "header.html" %}

<h1>Users</h1>
<h2>Actions</h2>
<ul>
<li><a href="{% url 'users:list' %}">List Users</a></li>
</ul>

{% include "footer.html" %}

StudentOrganization/templates/users/list.html
{% include "header.html" %}

{% for user in users %}
<a href="{% url 'users:detail' user.id %}">{{ user.username }}</a> <br/>
{% empty %}
No users exist
{% endfor %}

{% include "footer.html" %}